builders:
  keyMapGeneratorBuilder:
    import: 'package:flutter_key_map/my_generators.dart'
    builder_factories: ['keyMapGeneratorBuilder']
    auto_apply: dependents
    build_extensions: {".dart": [".info.part"]}
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]